name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configuração do Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # 3. Limpar o cache anterior (opcional, para garantir consistência)
      - name: Clear Cache
        run: |
          rm -rf .next out docs

      # 4. Instalação de dependências
      - name: Install dependencies
        run: npm install

      # 5. Build do projeto
      - name: Build the application
        run: npm run build

      # 6. Mover saída para a pasta docs
      - name: Move output to docs folder
        run: |
          rm -rf docs
          mkdir docs
          cp -R out/. docs

      # 7. Commit e push para o repositório
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Deploy to GitHub Pages"
          git push https://alinenink:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/alinenink/alineninkfinancas.github.io.git
